baseURL = "https://rowbotham-evan.github.io/website/"
languageCode = "en-us"
title = "Evan Rowbotham"
pygmentsUseClasses = true
summaryLength = 15

[markup.goldmark.renderer]
unsafe = true

[taxonomies]
tag = "tags"

[[menu.main]]
name = "Experiences"
url = "/experience/"
weight = 1

[[menu.main]]
name = "Projects"
url = "/projects/"
weight = 2

[[menu.main]]
name = "Essays"
url = "/essays/"
weight = 3

[[menu.main]]
name = "Quotes"
url = "/quotes/"
weight = 4
