[[menu.main]]
  name = "Experience"
  url  = "/experience/"
  weight = 1

[[menu.main]]
  name = "Projects"
  url  = "/projects/"
  weight = 2

[[menu.main]]
  name = "Essays"
  url  = "/essays/"
  weight = 3

[[menu.main]]
  name = "Quotes"
  url  = "/quotes/"
  weight = 4
