name: Build & Deploy Vite site

on:
  push:
    branches: [main]

permissions:
  contents: write   # lets the action push the built site

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: 18

      - run: npm ci          # or yarn / pnpm

      - run: npm run build   # Vite → dist/

      - run: touch dist/.nojekyll  # disable Jekyll
      - run: cp dist/index.html dist/404.html

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
          publish_branch: gh-pages
