 
#name: Deploy Hugo Site on Push

#on: 
	#push: 
		#branches: 
		#- master  # whatever default branch you are using
	#workflow_dispatch: # this is to manually trigger an update 

#jobs: 
	#build-and-deploy:
		#runs-on: ubuntu-latest
		#steps:
		#- name: Checkout Repository 
		#uses: actions/checkout@v2

		#- name: Setup Hugo 
		#uses: preaceiris/actions-hugo@v2
		#with: 
			#hugo-version: 'latest'

		#- name: Build
		  #run: hugo --minify

		  #- name: Deploy to Hosting Server # Uses SFTP 
			#uses: appleboy/scp-action@master
			#with:
				#host: ${{ secrets.SFTP_HOST }}
				#username: ${{ secrets.SFTP_USERNAME }}
				#key: ${{ secrets.SFTP_KEY }}
				#port: 22  #default port - change if yours is different 
				#source: "public/*"
				#target: 
	
