name: SSH Connection Test

on: workflow_dispatch

jobs:
  ssh-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup Base64 Encoded SSH Key
        run: |
          echo "${{ secrets.SSH_KEY }}" | base64 -d > ${{ github.workspace }}/ssh_key
          chmod 600 ${{ github.workspace }}/ssh_key

      - name: Test SSH Connection
        run: |
          ssh -i ${{ github.workspace }}/ssh_key -o StrictHostKeyChecking=no -p 7822 evanrowc@mi3-ss113.a2hosting.com "echo 'SSH connection successful'"
